%ifndef SYSCALL_INC
%define SYSCALL_INC

%define SYS_CALL_NO_SETUP			0
%define SYS_CALL_NO_EXIT			1
%define SYS_CALL_NO_FORK			2
%define SYS_CALL_NO_READ			3
%define SYS_CALL_NO_WRITE			4
%define SYS_CALL_NO_OPEN			5
%define SYS_CALL_NO_CLOSE			6
%define SYS_CALL_NO_WAITPID			7
%define SYS_CALL_NO_CREAT			8
%define SYS_CALL_NO_EXECV			11
%define SYS_CALL_NO_GETPID			20
%define SYS_CALL_NO_MOUNT			21
%define SYS_CALL_NO_UMOUNT			22
%define SYS_CALL_NO_ALARM			27
%define SYS_CALL_NO_PAUSE			29

%endif
